### ISSUE TITLE
Weird spacing beetwen block to tabs included separetely

### ISSUE THREAD

**Issue by tinesoft** [VersifitTechnologies/angular-ui-tab-scroll#3]
Hi,

First of all, thanks for this great library!

Now, i am facing a weird problem when wrapping a **tabset** with tabs included separately, ie either via
single **tab** elements added manually in the DOM, either via group of tab added by use of  **ng-repeat**:

![image](https://cloud.githubusercontent.com/assets/4053092/8144597/c2209eaa-11e5-11e5-94ad-ba541436c5fd.png)

See this [plunker](http://plnkr.co/edit/aloZvFN65owbTWf0AsW5?p=preview).

I inspected/compared the css of each block, but there is no difference...

Any idea?

Thanks

**Comment by seiyria** [comment]
Honestly, I've got no idea. Looks like you can get around it if you make the items that have `margin-right: 2px` into `margin-right: -4px`, it works ok. This isn't really a use case I tested as this was a pretty quick thing.

Thanks for using it! If you have a more elegant fix, feel free to send a PR.

**Comment by tinesoft** [comment]
Hi seiyria,

Thanks for the quick answer. 

Indeed, the **_margin-right: -4px**_ did the trick!

At first,  i changed it on the element **.nav-tabs > li > a**  (from **2px** to **-4px**) : but it was only working between the currently active tab and the direct next one (the other tabs were still spaced).

But then, thanks your answer and this [one](http://stackoverflow.com/questions/30819831/angular-ui-tab-scroll-weird-spacing-beetwen-block-to-tabs-included-separetely)  i've got from Stackoverflow, i've found [THE explanation](https://css-tricks.com/fighting-the-space-between-inline-block-elements/) of what is the normal behavior of **_Inlined Block Elements**_.

So finally I've added it  to the **.ui-tabs-scrollable .nav > li** instead, and it working like a charm!

FROM:

``` css
.ui-tabs-scrollable .nav > li {
  float: none;
  display: inline-block;
  margin-right: -4px;
  height: 42px!important;
  border-bottom: 1px solid #ddd;
}
```

TO:

``` css
.ui-tabs-scrollable .nav > li {
  margin-right: -4px;    /** Magic happens here**/
  float: none;
  display: inline-block;
  height: 42px!important;
  border-bottom: 1px solid #ddd;
}
```

I have submitted  a PR#4 with that small change

Thanks again
